[package]
name = "abi-decoding"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
extism-pdk = "1.3.0"
iron-functions-sdk = "0.9.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
ethabi-decode = "2.0.0"
hex = "0.4.3"
